project:
  type: default
  output-dir: _output
  render: ["**/*.qmd"]
format:
  revealjs:
    theme: [default]
    hash: true
    slide-number: true
    menu: false
    pdf-separate-fragments: false
    revealjs-plugins: [course-navigation]
    course-nav:
      sidebar: false
metadata-files: [_bsu.yml]
course-presentation:
  mode: study
lang: ru
number-sections: false

profile:
  default: student
  group: [[student, full]]

course:
  schema: "1.1"
  id: programming-practice
  validate: true
filters: [course-core, course-presentation]
