project:
  type: default
  render: [index.qmd]
  output-dir: _output/default
  pre-render: [_extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts]
  post-render: [_extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts]
  resources: ['!_generated/**', '!_extensions/**']
format: html
filters: [course-core]
course:
  id: example-exports
profile:
  default: student
  group: [[student, full]]
