project:
  type: default
  output-dir: _output
  render: ["**/*.qmd"]
format:
  revealjs:
    theme: simple
    hash: true
    slide-number: true
lang: ru
number-sections: false

profile:
  default: student
  group: [[student, full]]

course:
  schema: "1.0"
  id: programming-lectures
  validate: true
filters: [course-core]
