project:
  type: book
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/_*.qmd'
  - '!_generated/**'
  - '!_freeze/**'
  - '!.quarto/**'
  pre-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
  - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
  - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: student
  group:
  - - student
    - full
course:
  id: course-handbook
filters:
- course-core
- course-presentation
- reference-catalog
course-presentation:
  mode: study
book:
  sidebar:
    tools:
    - icon: house
      href: ../index.html#sec-portal
      text: Навигация курса
  title: Справочник
  chapters:
  - index.qmd
format:
  html:
    theme: cosmo
lang: ru
reference-catalog:
  namespace: handbook
