project:
  type: book
  output-dir: _book
  resources:
    - "!**/projects/**"
    - "!**/_control.qmd"
    - "!_generated/**"
book:
  title: Программирование
  chapters:
    - index.qmd
    - topics/contracts/index.qmd
    - topics/contracts/demonstration.qmd
    - labs/01.qmd
format:
  html:
    theme: cosmo
lang: ru
course:
  schema: "1.0"
  id: programming
  validate: true
filters:
  - course-core
  - course-cloud
  - course-prairielearn

profile:
  default: student
  group: [[student, full]]
